services:
  quartz-caddy:
    image: quartz-caddy:latest
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./quartz-caddy/config:/config/
      - ./quartz-caddy/config/content:/config/content
