services:
  quartz-caddy:
    image: quartz-caddy:latest
    build:
      context: .
      ssh:
        - default
    ports:
      - "80:80"
    volumes:
      - ./quartz:/config/quartz
    environment:
