services:
  web:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - quartz-public:/srv
      - caddy-data:/data
      - caddy-config:/config

  quartz:
    image: alpine:latest
    restart: unless-stopped
    command: sh

volumes:
  caddy-data:
  caddy-config:
  quartz-public:

