services:
  web:
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - web-data:/data
      - web-config:/config
      - quartz-output:/srv/public


  quartz:
    image: quartz-builder:latest
    restart: unless-stopped
    volumes:
      - ./quartz:/opt/quartz/
      - quartz-output:/opt/public

volumes:
  web-data:
  web-config:
  quartz-output:

