services:
  web:
    image: caddy:latest
    image: dalgardnerd/quartz-caddy:latest
    depends_on: 
      - quartz-builder
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
    volumes:
      - web-data:/data
      - web-config:/config
      - quartz-output:/srv/public

      - type: volume
        source: quartz
        target: /srv/public
        volume:
          subpath: public

  quartz-builder:
    image: dalgardnerd/quartz-builder:latest
    restart: unless-stopped
    volumes:
      - ./quartz:/opt/quartz/
      - quartz-output:/opt/public
      - quartz:/opt

  vs-code:
    image: linuxserver/code-server
    restart: unless-stopped
    ports:
      - "8443:8443"
    volumes:
      - quartz:/data
    working_dir: /data

volumes:
  web-data:
  web-config:
  quartz-output:  quartz: